cloud:
  aws:
    credentials:
      access-key: 
      secret-key: 
    region:
      static: us-east-1
    stack:
      auto: false

application:
  bucket:
    name: xmlziofilessmarsh


spring:
  servlet:
    multipart:
      max-file-size: 2048MB
      max-request-size: 2048MB

#server:
 # port: 8090
